#COMMANDS
COUNT_SUBSTRINGS = 'C'
MOLECULAR_FORMULA = 'M'
DISSIMILARITY = 'D'
INPUT = 'I'
HELP = 'H'
QUIT = 'Q'
NO = 'N'
YES = 'Y'

#INTERACTIONS
LOAD_SOURCE = 'Load input from file (Y/N)?\n'
INPUT_COMMAND = 'Input command to execute:'
INPUT_SOURCE = 'Input source (F/T): \n'
INPUT_FILE_NAME = 'Input file name: '
SAVE_SMILES = 'Save SMILES list to file (Y/N)?\n'
GOODBYE = 'Goodbye.'
LIST_IS_EMPTY = 'SMILES list empty'
HELP_MESSAGE = 'Help Message'
PROMPT = '> \n'
FILE = 'F'
TERMINAL = 'T'

#ERRORS
FAILED_READING = 'Failed reading file '
INVALID_ANSWER = 'Answer invalid'
LIST_EMPTY = 'SMILES list empty'
INVALID_COMMAND = 'Command invalid'
SMILES_INVALID = 'String s is not a valid SMILES'
SMILES_ALREADY_LOADED = 'SMILES s already loaded'
SMILES_INSERTED  = 'SMILES list updated: s inserted'
INVALID_INPUT = 'Input invalid'
LIST_EMPTY_OR_SINGULAR = 'SMILES list empty or singular'
NUMBER_OF_SUBSTRINGS = 'How many structures (enter a positive number):\n'
COMPARE_STRINGS = 'Give two SMILES to compare:'
#UNKNOWN_SMILES_1 = 'SMILES s1 unknown; input a valid one:'
#UNKNOWN_SMILES_2 = 'SMILES s2 unknown; input a valid one:'

#Functions
INPUT_NEW_SMILES = 'Enter new smiles '